$ErrorActionPreference = "Stop"

$out = Join-Path $PSScriptRoot "hub_shell_portals.obj"
$segments = 32
$portalHalfAngle = 12.0

$rings = @(
    @{ y = -2.0; r = 13.0 },
    @{ y =  0.0; r = 16.2 },
    @{ y =  4.4; r = 16.2 },
    @{ y =  8.2; r = 14.6 },
    @{ y = 11.6; r = 11.6 },
    @{ y = 14.2; r =  6.5 }
)

$culture = [System.Globalization.CultureInfo]::InvariantCulture
$vertices = New-Object System.Collections.Generic.List[object]
$faces = New-Object System.Collections.Generic.List[object]

function Add-Vertex([double]$x, [double]$y, [double]$z) {
    $script:vertices.Add([pscustomobject]@{ x = $x; y = $y; z = $z })
    return $script:vertices.Count
}

function Add-Tri([int]$a, [int]$b, [int]$c) {
    $script:faces.Add(@($a, $b, $c))
}

function Is-Portal-Segment([double]$angleDeg) {
    foreach ($axis in @(0.0, 90.0, 180.0, 270.0)) {
        $delta = [math]::Abs((($angleDeg - $axis + 540.0) % 360.0) - 180.0)
        if ($delta -lt $script:portalHalfAngle) {
            return $true
        }
    }
    return $false
}

$ringIds = @()
foreach ($ring in $rings) {
    $ids = @()
    for ($i = 0; $i -lt $segments; $i++) {
        $angle = (2.0 * [math]::PI * $i) / $segments
        $ids += Add-Vertex ([math]::Cos($angle) * $ring.r) $ring.y ([math]::Sin($angle) * $ring.r)
    }
    $ringIds += ,$ids
}

for ($r = 0; $r -lt $rings.Count - 1; $r++) {
    for ($i = 0; $i -lt $segments; $i++) {
        $next = ($i + 1) % $segments
        $midAngle = (($i + 0.5) * 360.0) / $segments
        $isPortalBand = $r -le 1

        if ($isPortalBand -and (Is-Portal-Segment $midAngle)) {
            continue
        }

        $a = $ringIds[$r][$i]
        $b = $ringIds[$r][$next]
        $c = $ringIds[$r + 1][$next]
        $d = $ringIds[$r + 1][$i]

        Add-Tri $a $b $c
        Add-Tri $a $c $d
    }
}

$topCenter = Add-Vertex 0.0 15.4 0.0
$topRing = $ringIds[$rings.Count - 1]
for ($i = 0; $i -lt $segments; $i++) {
    $next = ($i + 1) % $segments
    Add-Tri $topRing[$i] $topRing[$next] $topCenter
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Faceted hub shell with designed tunnel portals")
$lines.Add("# Generated by gen_hub_shell.ps1")
$lines.Add("# $($vertices.Count) vertices, $($faces.Count) triangles")
$lines.Add("")
foreach ($v in $vertices) {
    $lines.Add(("v {0} {1} {2}" -f $v.x.ToString("F6", $culture), $v.y.ToString("F6", $culture), $v.z.ToString("F6", $culture)))
}
$lines.Add("")
foreach ($f in $faces) {
    $lines.Add(("f {0}/{0} {1}/{1} {2}/{2}" -f $f[0], $f[1], $f[2]))
}

Set-Content -Path $out -Value $lines -Encoding ascii
Write-Host "Wrote $out with $($vertices.Count) vertices and $($faces.Count) triangles"
