#!/usr/bin/env python3
"""Generate icosahedron_hub_cut.obj with tunnel cutouts.

The original hub mesh has large triangles. Removing whole faces creates huge
holes, so this generator subdivides faces first and removes only small pieces
inside the tunnel profiles.
"""
from __future__ import annotations

from pathlib import Path
import math

HERE = Path(__file__).resolve().parent
IN_FILE = HERE / "icosahedron_hub.obj"
OUT_FILE = HERE / "icosahedron_hub_cut.obj"

SUBDIVISION_LEVELS = 4

# Coordinates are in the unscaled OBJ space. app.cpp scales the hub by 1.45.
PORTAL_BOTTOM = -0.8
PORTAL_TOP = 3.6
PORTAL_HALF_WIDTH = 2.85
PORTAL_SHOULDER = 2.15


def lerp(a, b, t):
    return (
        a[0] + (b[0] - a[0]) * t,
        a[1] + (b[1] - a[1]) * t,
        a[2] + (b[2] - a[2]) * t,
    )


def midpoint(a, b):
    return lerp(a, b, 0.5)


def subdivide(tri, levels):
    if levels <= 0:
        return [tri]

    a, b, c = tri
    ab = midpoint(a, b)
    bc = midpoint(b, c)
    ca = midpoint(c, a)

    result = []
    for child in ((a, ab, ca), (ab, b, bc), (ca, bc, c), (ab, bc, ca)):
        result.extend(subdivide(child, levels - 1))
    return result


def half_width_at_y(y):
    if y < PORTAL_BOTTOM or y > PORTAL_TOP:
        return -1.0

    bottom_chamfer_top = PORTAL_BOTTOM + 0.75
    top_chamfer_bottom = PORTAL_TOP - 0.75

    if y < bottom_chamfer_top:
        t = (y - PORTAL_BOTTOM) / (bottom_chamfer_top - PORTAL_BOTTOM)
        return PORTAL_SHOULDER + (PORTAL_HALF_WIDTH - PORTAL_SHOULDER) * t
    if y > top_chamfer_bottom:
        t = (PORTAL_TOP - y) / (PORTAL_TOP - top_chamfer_bottom)
        return PORTAL_SHOULDER + (PORTAL_HALF_WIDTH - PORTAL_SHOULDER) * t
    return PORTAL_HALF_WIDTH


def inside_portal_profile(side_coord, y):
    return abs(side_coord) <= half_width_at_y(y)


def inside_any_tunnel(p):
    x, y, z = p
    return inside_portal_profile(z, y) or inside_portal_profile(x, y)


def parse_obj(path):
    vertices = []
    faces = []

    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("v "):
            _, x, y, z = line.split()
            vertices.append((float(x), float(y), float(z)))
        elif line.startswith("f "):
            parts = line.split()[1:]
            ids = [int(part.split("/")[0]) - 1 for part in parts]
            faces.append(tuple(vertices[i] for i in ids))

    return vertices, faces


def main():
    _, faces = parse_obj(IN_FILE)
    cut_faces = []

    for face in faces:
        for tri in subdivide(face, SUBDIVISION_LEVELS):
            centroid = (
                (tri[0][0] + tri[1][0] + tri[2][0]) / 3.0,
                (tri[0][1] + tri[1][1] + tri[2][1]) / 3.0,
                (tri[0][2] + tri[1][2] + tri[2][2]) / 3.0,
            )
            if not inside_any_tunnel(centroid):
                cut_faces.append(tri)

    out_vertices = []
    out_faces = []
    vertex_index = {}

    for tri in cut_faces:
        face = []
        for p in tri:
            key = tuple(round(v, 6) for v in p)
            if key not in vertex_index:
                vertex_index[key] = len(out_vertices) + 1
                out_vertices.append(key)
            face.append(vertex_index[key])
        out_faces.append(tuple(face))

    lines = [
        "# Truncated icosahedron hub shell with four subdivided tunnel cutouts",
        f"# Generated by gen_icosa_cut.py from {IN_FILE.name}",
        f"# {len(out_vertices)} vertices, {len(out_faces)} triangles",
        "",
    ]
    for x, y, z in out_vertices:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    lines.append("")
    for a, b, c in out_faces:
        lines.append(f"f {a}/{a} {b}/{b} {c}/{c}")

    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"Wrote {OUT_FILE} with {len(out_faces)} triangles")


if __name__ == "__main__":
    main()
