$ErrorActionPreference = "Stop"

$fillOut = Join-Path $PSScriptRoot "hub_shell_portals.obj"
$edgeOut = Join-Path $PSScriptRoot "hub_shell_edges.obj"
$culture = [System.Globalization.CultureInfo]::InvariantCulture

$fillVertices = New-Object System.Collections.Generic.List[object]
$fillFaces = New-Object System.Collections.Generic.List[object]
$edgeVertices = New-Object System.Collections.Generic.List[object]
$edgeFaces = New-Object System.Collections.Generic.List[object]

function V3([double]$x, [double]$y, [double]$z) {
    return [pscustomobject]@{ x = $x; y = $y; z = $z }
}

function AddV($a, $b) { return V3 ($a.x + $b.x) ($a.y + $b.y) ($a.z + $b.z) }
function MulV($a, [double]$s) { return V3 ($a.x * $s) ($a.y * $s) ($a.z * $s) }
function DotV($a, $b) { return $a.x * $b.x + $a.y * $b.y + $a.z * $b.z }
function CrossV($a, $b) { return V3 (($a.y * $b.z) - ($a.z * $b.y)) (($a.z * $b.x) - ($a.x * $b.z)) (($a.x * $b.y) - ($a.y * $b.x)) }
function LenV($a) { return [math]::Sqrt((DotV $a $a)) }
function NormV($a) {
    $len = LenV $a
    if ($len -lt 0.000001) { return V3 0.0 1.0 0.0 }
    return MulV $a (1.0 / $len)
}

function Add-Vertex($list, $p) {
    [void]$list.Add($p)
    return $list.Count
}

function Add-Tri($list, [int]$a, [int]$b, [int]$c) {
    [void]$list.Add(@($a, $b, $c))
}

function Angle-Distance([double]$angleDeg, [double]$axisDeg) {
    return [math]::Abs((($angleDeg - $axisDeg + 540.0) % 360.0) - 180.0)
}

function Is-Portal-Panel([double]$angleDeg, [double]$y) {
    if ([math]::Abs($y - $script:portalPanelY) -gt 0.2) {
        return $false
    }

    foreach ($axis in @(0.0, 90.0, 180.0, 270.0)) {
        if ((Angle-Distance $angleDeg $axis) -lt 10.0) {
            return $true
        }
    }
    return $false
}

function Add-Hex-Panel($center, $normal, [double]$radius, [double]$frameWidth) {
    $n = NormV $normal
    $up = V3 0.0 1.0 0.0
    $u = CrossV $up $n
    if ((LenV $u) -lt 0.001) {
        $u = CrossV (V3 1.0 0.0 0.0) $n
    }
    $u = NormV $u
    $v = NormV (CrossV $n $u)

    $innerRadius = $radius - $frameWidth
    $outer = @()
    $inner = @()

    for ($i = 0; $i -lt 6; $i++) {
        $a = (2.0 * [math]::PI * $i) / 6.0
        $outer += AddV $center (AddV (MulV $u ([math]::Cos($a) * $radius)) (MulV $v ([math]::Sin($a) * $radius)))
        $inner += AddV (AddV $center (MulV $n 0.035)) (AddV (MulV $u ([math]::Cos($a) * $innerRadius)) (MulV $v ([math]::Sin($a) * $innerRadius)))
    }

    $fillCenter = Add-Vertex $script:fillVertices (AddV $center (MulV $n 0.04))
    $fillIds = @()
    for ($i = 0; $i -lt 6; $i++) {
        $fillIds += Add-Vertex $script:fillVertices $inner[$i]
    }
    for ($i = 0; $i -lt 6; $i++) {
        $next = ($i + 1) % 6
        Add-Tri $script:fillFaces $fillCenter $fillIds[$i] $fillIds[$next]
    }

    $outerIds = @()
    $innerIds = @()
    for ($i = 0; $i -lt 6; $i++) {
        $outerIds += Add-Vertex $script:edgeVertices $outer[$i]
        $innerIds += Add-Vertex $script:edgeVertices $inner[$i]
    }
    for ($i = 0; $i -lt 6; $i++) {
        $next = ($i + 1) % 6
        Add-Tri $script:edgeFaces $outerIds[$i] $outerIds[$next] $innerIds[$next]
        Add-Tri $script:edgeFaces $outerIds[$i] $innerIds[$next] $innerIds[$i]
    }
}

function Write-Obj([string]$path, [string]$title, $vertices, $faces) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add($title)
    $lines.Add("# Generated by gen_hub_shell.ps1")
    $lines.Add("# $($vertices.Count) vertices, $($faces.Count) triangles")
    $lines.Add("")

    foreach ($vtx in $vertices) {
        $lines.Add(("v {0} {1} {2}" -f $vtx.x.ToString("F6", $culture), $vtx.y.ToString("F6", $culture), $vtx.z.ToString("F6", $culture)))
    }

    $lines.Add("")
    foreach ($face in $faces) {
        $lines.Add(("f {0}/{0} {1}/{1} {2}/{2}" -f $face[0], $face[1], $face[2]))
    }

    Set-Content -Path $path -Value $lines -Encoding ascii
}

$panelRadius = 2.35
$portalPanelY = 1.7931034483

# Rows of tangent hexagon panels. Counts are chosen from the hex panel radius
# so the panel pitch stays consistent around the portal row.
$rows = @(
    @{ y = -2.05;           r = 15.7; count = 28; offset = 6.4285714286; size = $panelRadius },
    @{ y = $portalPanelY;   r = 16.3; count = 28; offset = 0.0;          size = $panelRadius },
    @{ y =  5.65;           r = 15.1; count = 24; offset = 7.5;          size = $panelRadius },
    @{ y =  9.15;           r = 11.6; count = 20; offset = 0.0;          size = 2.25 },
    @{ y = 11.85;           r =  7.2; count = 12; offset = 15.0;         size = 2.10 }
)

foreach ($row in $rows) {
    for ($i = 0; $i -lt $row.count; $i++) {
        $angleDeg = $row.offset + (($i * 360.0) / $row.count)
        if (Is-Portal-Panel $angleDeg $row.y) {
            continue
        }

        $angle = $angleDeg * [math]::PI / 180.0
        $center = V3 ([math]::Cos($angle) * $row.r) $row.y ([math]::Sin($angle) * $row.r)
        $normal = NormV (V3 $center.x ($center.y - 2.0) $center.z)
        Add-Hex-Panel $center $normal $row.size 0.32
    }
}

Add-Hex-Panel (V3 0.0 13.1 0.0) (V3 0.0 1.0 0.0) 2.15 0.32

Write-Obj $fillOut "# Hub dome solid hexagonal panels" $fillVertices $fillFaces
Write-Obj $edgeOut "# Hub dome dark hexagonal panel frames" $edgeVertices $edgeFaces
Write-Host "Wrote $fillOut with $($fillVertices.Count) vertices and $($fillFaces.Count) triangles"
Write-Host "Wrote $edgeOut with $($edgeVertices.Count) vertices and $($edgeFaces.Count) triangles"
