#!/usr/bin/env python3
"""Generate hex_pedestal.obj — hexagonal platform with 6 railing posts and top rail bars."""
import math

PLAT_R   = 2.8    # platform outer hex radius
PLAT_H   = 0.70   # platform height
POST_W   = 0.11   # post half-width (square cross-section)
POST_H   = 1.30   # post height above platform top
RAIL_W   = 0.06   # railing bar half-width (along edge)
RAIL_T   = 0.06   # railing bar half-thickness

all_verts = []
all_faces = []   # 1-indexed OBJ faces (v_idx triplets)

def av(x, y, z):
    all_verts.append((x, y, z))
    return len(all_verts)          # 1-indexed

def add_box(cx, cy, cz, dx, dy, dz, ry_deg=0.0):
    hw, hh, hd = dx/2, dy/2, dz/2
    raw = [
        (-hw,-hh,-hd),(+hw,-hh,-hd),(+hw,-hh,+hd),(-hw,-hh,+hd),
        (-hw,+hh,-hd),(+hw,+hh,-hd),(+hw,+hh,+hd),(-hw,+hh,+hd),
    ]
    cr = math.cos(math.radians(ry_deg))
    sr = math.sin(math.radians(ry_deg))
    def ry(v):
        x, y, z = v
        return (x*cr + z*sr, y, -x*sr + z*cr)
    idxs = [av(rv[0]+cx, rv[1]+cy, rv[2]+cz) for rv in (ry(v) for v in raw)]
    b0,b1,b2,b3,t0,t1,t2,t3 = idxs
    all_faces.extend([
        (b0,b2,b1),(b0,b3,b2),
        (t0,t1,t2),(t0,t2,t3),
        (b0,b1,t1),(b0,t1,t0),
        (b1,b2,t2),(b1,t2,t1),
        (b2,b3,t3),(b2,t3,t2),
        (b3,b0,t0),(b3,t0,t3),
    ])

def add_hex_prism(cx, cy, cz, r, h, angle_off_deg=30.0):
    n = 6
    bot, top = [], []
    for i in range(n):
        a = math.radians(angle_off_deg + i * 60)
        bot.append(av(cx + r*math.cos(a), cy,   cz + r*math.sin(a)))
        top.append(av(cx + r*math.cos(a), cy+h, cz + r*math.sin(a)))
    # bottom cap (normals down)
    for i in range(1, n-1):
        all_faces.append((bot[0], bot[i+1], bot[i]))
    # top cap (normals up)
    for i in range(1, n-1):
        all_faces.append((top[0], top[i], top[i+1]))
    # side quads
    for i in range(n):
        j = (i+1) % n
        all_faces.append((bot[i], bot[j], top[j]))
        all_faces.append((bot[i], top[j], top[i]))
    return [(cx + PLAT_R*math.cos(math.radians(angle_off_deg + i*60)),
             cz + PLAT_R*math.sin(math.radians(angle_off_deg + i*60)))
            for i in range(n)]

# ── Platform hex prism ────────────────────────────────────────────────────────
post_xz = add_hex_prism(0, 0, 0, PLAT_R, PLAT_H, angle_off_deg=30.0)

# ── 6 railing posts at each vertex ───────────────────────────────────────────
post_y_center = PLAT_H + POST_H / 2
for px, pz in post_xz:
    add_box(px, post_y_center, pz, POST_W*2, POST_H, POST_W*2)

# ── 6 railing bars along each edge ───────────────────────────────────────────
rail_y = PLAT_H + POST_H - RAIL_T          # top of posts
edge_len   = PLAT_R                         # regular hex: edge = radius
r_mid      = PLAT_R * math.cos(math.radians(30))  # center→edge-midpoint
for i in range(6):
    a_mid_deg = 30 + i*60 + 30             # angle to midpoint between vertex i and i+1
    a_mid     = math.radians(a_mid_deg)
    bx = r_mid * math.cos(a_mid)
    bz = r_mid * math.sin(a_mid)
    add_box(bx, rail_y, bz, edge_len, RAIL_T*2, RAIL_W*2, ry_deg=-(a_mid_deg))

# ── Write OBJ ────────────────────────────────────────────────────────────────
lines = [
    '# Hexagonal pedestal with guardrail — generated by gen_hex_pedestal.py',
    f'# {len(all_verts)} verts, {len(all_faces)} triangles',
    '',
]
for x, y, z in all_verts:
    lines.append(f'v {x:.5f} {y:.5f} {z:.5f}')
lines.append('')
for a, b, c in all_faces:
    lines.append(f'f {a} {b} {c}')

out = 'objects/hex_pedestal.obj'
with open(out, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f'Written {len(all_verts)} verts, {len(all_faces)} tris to {out}')
